#ifndef ENROLL32_CONSTANTS_H
#define ENROLL32_CONSTANTS_H

#define LIST L"listbox"
#define EDIT L"edit"
#define BUTTON L"button"

const int MARGIN = 10;
const int MARGIN_HALF = MARGIN / 2;

const int WIDTH = 600;
const int HEIGHT = 600;

const int LIST_HEIGHT = HEIGHT / 12 * 9;
const int LIST_WIDTH = WIDTH / 2;

const int BUTTON_WIDTH = WIDTH / 4;
const int BUTTON_HEIGHT = HEIGHT / 12;

struct LAYOUT_PARAMS {
    LAYOUT_PARAMS(int x, int y, int w, int h) : x(x), y(y), w(w), h(h) {}

    int x, y, w, h;
};

const LAYOUT_PARAMS ListLeft(MARGIN_HALF, MARGIN_HALF, LIST_WIDTH - MARGIN, LIST_HEIGHT - MARGIN);
const LAYOUT_PARAMS ListRight(LIST_WIDTH + MARGIN_HALF, MARGIN_HALF, LIST_WIDTH - MARGIN, LIST_HEIGHT - MARGIN);

const LAYOUT_PARAMS ButtonAdd(
        MARGIN_HALF, LIST_HEIGHT + MARGIN_HALF, BUTTON_WIDTH - MARGIN, BUTTON_HEIGHT - MARGIN
);

const LAYOUT_PARAMS ButtonClear(
        BUTTON_WIDTH + MARGIN_HALF, LIST_HEIGHT + MARGIN_HALF, BUTTON_WIDTH - MARGIN, BUTTON_HEIGHT - MARGIN
);

const LAYOUT_PARAMS ButtonToRight(
        2 * BUTTON_WIDTH + MARGIN_HALF, LIST_HEIGHT + MARGIN_HALF, BUTTON_WIDTH - MARGIN, BUTTON_HEIGHT - MARGIN
);

const LAYOUT_PARAMS ButtonDelete(
        3 * BUTTON_WIDTH + MARGIN_HALF, LIST_HEIGHT + MARGIN_HALF, BUTTON_WIDTH - MARGIN, BUTTON_HEIGHT - MARGIN
);

const LAYOUT_PARAMS Input(
        MARGIN_HALF, LIST_HEIGHT + BUTTON_HEIGHT + MARGIN_HALF, WIDTH - MARGIN, BUTTON_HEIGHT - MARGIN
);

const int ADD_ID = 1001;
const int CLEAR_ID = 1002;
const int TO_RIGHT_ID = 1003;
const int DELETE_ID = 1004;

#endif //ENROLL32_CONSTANTS_H
